sudo: required
services: 
  - docker
before_install:
# Il tag dell'immagine e' usato solo dentro travis
  - docker build -t pancix/docker-react -f Dockerfile.dev .
script: 
  - docker run pancix/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "udemyL83-docker-react"
  env: Udemyl83DockerReact-env
  bucket_name: "elasticbeanstalk-us-east-1-235903008164"
  bucket_path: "udemyL83-docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secure:
    secret_access_key: "$AWS_SECRET_KEY"

