sudo: required
services:
- docker
before_install:
- docker build -t pancix/docker-react -f Dockerfile.dev .
script:
- docker run pancix/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  region: us-east-1
  app: udemyL83-docker-react
  env: Udemyl83DockerReact-env
  on:
    repo: Panciz/udemyL83-docker-react
  bucket-name: "elasticbeanstalk-us-east-1-235903008164"
  bucket-path: udemyL83-docker-react
